### ISSUE TITLE
Configurator doesn't show target locations correctly if the target units are in inches

### ISSUE THREAD

**Issue by akarras** [EverythingSmartHome/everything-presence-addons#14]
My instance settings seem to change the units of the targets to inches which seems to also break the visualization.
<img width="1215" alt="Screenshot 2024-11-22 at 9 35 14 AM" src="https://github.com/user-attachments/assets/e7917bf5-cf42-4869-b179-7dbaad976831">
<img width="305" alt="Screenshot 2024-11-22 at 9 37 15 AM" src="https://github.com/user-attachments/assets/3f22ce19-1a7e-4f32-b9e1-734fcf42a5e3">

Changing the units resolves the issue, but I imagine it's confusing for certain US based users.

**Comment by akarras** [comment]
Yeah, I think it makes sense to have the configurator always show mm since that ultimately is how these zones are configured. Can we take the unit of measurement from the state response and convert that to mm in the js frontend?
```json
{
	"attributes": {
                ..omitting fields
		"unit_of_measurement": "in" // <-- pull this guy out
	},
       ..omitting fields
	"state": "12.0" // <-- convert this state from in to mm so we're accurately showing the units. 
}
```

**Comment by EverythingSmartHome** [comment]
Yes I'm sure its certainly possible to have it work in inches at some point, just a lower priority at the moment. But by all means if you have the skills, a PR would be awesome!

**Comment by randomletters** [comment]
I am also experiencing this.  I don't think I configured it for inches.  Maybe it is using a default in Home Assistant?

**Comment by akarras** [comment]
To work around this issue you have to go to the device in home assistant and manually change each sensor to mm. I only did target 1 to get it dialed in, but definitely tedious doing it to every sensor/target combo 😅

**Comment by randomletters** [comment]
Confirmed.  I opened the device in home assistant, then I clicked on every entity in the "Sensors" section that had an "in" unit (about 4 per zone), clicked the cog to edit the entity, changed the unit from "in" to "mm", clicked update.  This made the configurator display the correct information.

**Comment by mizuxe** [comment]
I think it should at least warn people they might have to switch. Even in the documentation would be prefereable. I was lucky enough to find this thread, but I almost switched back to the old method and was losing my mind on that front.

**Comment by akarras** [comment]
Theoretically, I think I have the fix https://github.com/akarras/everything-presence-addons/commit/27d29bb4163ae41cc3b76ac30aa2cf93af3e4315

In practice, I haven't been able to test it- haven't done any HA dev... But it should work? I just made a function that converts the units to mm so we should be able to shove any entity through it to correct it.
I'll poke at it more tomorrow, but figured I'd get up what I have for now.
