### ISSUE TITLE
How about a 'Persistant' option - builds paths of traffic?

### ISSUE THREAD

**Issue by francismiles1** [EverythingSmartHome/everything-presence-addons#17]
Hi Lewis. Firstly, a much needed addon, many thanks. Quite similar to a plotly dashboard implementation I had, but far prefer this.

Just an idea: A 'Persistent' switch that doesn't remove dots. This will have the effect of aggregating routes in your room and visually plotting them, to identify exactly where items of furniture etc. are. Makes it easy to define zones!
thanks

**Comment by francismiles1** [comment]
So, I decided to just do it anyway. I have tried to check the code in, but made a real hash of the fork and most probably you cant see the new changes. Please let me know if not and I will send it over.
'I' Think it looks pretty cool! Its certainly really helpful for me to visualize furniture etc.
![image](https://github.com/user-attachments/assets/6872ff2e-9a92-444d-81e3-6e022e524605)

**Comment by EverythingSmartHome** [comment]
Awesome, cool addition! Thanks for submitting

**Comment by francismiles1** [comment]
Err, you may need to integrate this stuff incrementally. It would seem I made a bit of a mess creating and saving zones. Your original code works well, but my functionality integration seems to have messed it up a tad!!
