### ISSUE TITLE
Zone Configurator no data if enties are hidden

### ISSUE THREAD

**Issue by Oliver3911** [EverythingSmartHome/everything-presence-addons#25]
Everything Presence Zone Configurator shows no data if enties are hidden by user.

I have hidden many of the Sensors and config enties because I use Auto-enties Card on my dashboard. This causes the add-on to not show any data. Devices can still be selected, but then no data showes up.

**Comment by EverythingSmartHome** [comment]
There is unfortunately no way around this as far as I know, because when you hide the entities it means they are unavailable in the API

(At least that's my experience so far)
