### ISSUE TITLE
Target visualization scaling issue

### ISSUE THREAD

**Issue by eagleco** [EverythingSmartHome/everything-presence-addons#3]
I've tried opening the addon page from chrome browser on a windows desktop, a chromebook, and an android phone and on all 3 I'm seeing the same issue.  Target dot appears and moves around but stays very close to the origin, like the x,y coordinates need to be multiplied by some value to match the actual scale of the canvas.  Anything I can do to help diagnose?

Made sure esphome config was latest, restarted the addon, restarted the EPL, no change.

Excited about this functionality!

**Comment by EverythingSmartHome** [comment]
This issue occurs when you have the default unit of measurement changed to inches instead of mm. The default units for most of the sensors is in mm but your HA may be changing them to inches. Change those back and should work OK

**Comment by mhn10** [comment]
Yeah, I was facing the same issue. Went into Home Assistant Settings> System> General> Unit System> Celsius/Kilogram
