### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by LucidityCrash** [EverythingSmartHome/everything-presence-addons#36]
Would it be possible to make this somewhat more generic for other presence sensors (DIY and something like the Smart Home shop Ultimate sensor)
currently the [fetchDevices](https://github.com/EverythingSmartHome/everything-presence-addons/blob/caba6d843b768f8e319dbe59b2254b5cd8e9d03d/everything-presence-mmwave-configurator/www/script.js#L765C1-L778C9) function is obviously very EverythingSmartHome specific 😁  but this tool is pretty damn cool and I'm sure others would find it incredibly useful.

**Comment by EverythingSmartHome** [comment]
At the moment it's not planned, we are just focused on our own devices since we know what features it has, what the entity names are, how to look for those entity names, device names etc
