### ISSUE TITLE
Unable to add more than 1 zone

### ISSUE THREAD

**Issue by sa0cav** [EverythingSmartHome/everything-presence-addons#37]
When i try to add more than one zone only the first one will be saved and active. The other zones disappears.

**Comment by EverythingSmartHome** [comment]
You need to enable zones 2-4 in home assistant. Go into the device page and select hidden entities for zone 2-4. Click each entity, select the cog and enable

**Comment by sa0cav** [comment]
Omg, ofcourse! Thank you for the reply!

Den fre 13 dec. 2024 21:17Everything Smart Home ***@***.***>
skrev:
