### ISSUE TITLE
No Devices listed to select

### ISSUE THREAD

**Issue by thheller** [EverythingSmartHome/everything-presence-addons#39]
I have a Presence One and it is working fine in Home Assistant. Installed the Configurator to fiddle with some options, but it doesn't show any Devices to select, so I can't do anything. Browser console is clear, no errors as far as I can tell.

Addon log doesn't help much either.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun backend (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
ERROR:root:Running as a Home Assistant Add-on.
 * Serving Flask app 'backend'
 * Debug mode: off
```

![Screenshot 2024-12-17 121427](https://github.com/user-attachments/assets/61f2d9f3-c725-42a8-b9ad-da3e9d1897c1)

**Comment by EverythingSmartHome** [comment]
The add-on only works with the Everything Presence Lite as the add-on is primarily to configure zones and the Lite supports zones

**Comment by thheller** [comment]
Doh.

**Comment by Sc00tz** [comment]
@EverythingSmartHome Is there any plans for the One to support this add-on as well?

**Comment by fslef** [comment]
i was wondering about the same.
@EverythingSmartHome we all apreciate if you could add zones capabilities to the EP1 :)

**Comment by EverythingSmartHome** [comment]
I've spoke about this a fair bit, but its not possible as the sensor doesn't support it. I would recommend my last video on the EPL and EP1 changes where I talked about this and the reasons why if you are interested
